import json
import random

# Raw items from the 3 PDF pages
raw_data = [
    (1, "Saya tahu cara meyakinkan orang lain.", "S"),
    (2, "Saya berusaha mempengaruhi orang lain.", "STS"),
    (3, "Saya mengubah perencanaan menjadi Tindakan.", "S"),
    (4, "Saya menyelesaikan banyak pekerjaan.", "S"),
    (5, "Saya selalu bekerja/bertindak dengan terencana.", "S"),
    (6, "Saya meyakini segala sesuatu perlu dipikirkan secara seksama dan runtut.", "SS"),
    (7, "Saya cepat akrab dengan orang lain.", "SS"),
    (8, "Saya berusaha untuk melampaui pencapaian orang lain.", "S"),
    (9, "Saya merasa perlu menghargai keputusan-keputusan yang dibuat oleh kelompok.", "S"),
    (10, "Saya tidak banyak berbicara.", "SS"),
    (11, "Saya tidak suka melakukan hal-hal yang membuat orang lain memperhatikan saya.", "SS"),
    (12, "Saya mengerjakan pekerjaan yang tidak saya sukai sesegera mungkin.", "TS"),
    (13, "Saya membutuhkan dorongan untuk memulai suatu hal.", "S"),
    (14, "Saya sering terlambat datang bekerja.", "STS"),
    (15, "Saya menyelesaikan pekerjaan dengan usaha yang secukupnya.", "TS"),
    (17, "Saya kurang pandai membuat orang lain menyukai saya.", "SS"),
    (18, "Jika dibandingkan dengan orang lain, saya cenderung kurang menikmati berinteraksi dengan banyak orang.", "STS"),
    (19, "Saya tidak terlalu termotivasi untuk mencapai kesuksesan.", "STS"),
    (20, "Saya menghabiskan waktu dengan tidak melakukan apapun.", "STS"),
    (21, "Saya tidak pernah berprasangka buruk terhadap orang lain.", "SS"),
    (22, "Saya selalu ceria.", "SS"),
    (23, "Saya berusaha untuk memimpin orang lain.", "S"),
    (24, "Saya pandai dalam berpidato dadakan.", "TS"),
    (25, "Saya cepat dalam menyelesaikan banyak hal.", "S"),
    (26, "Saya mampu menyelesaikan pekerjaan tepat waktu.", "SS"),
    (27, "Saya menjalankan pekerjaan atau bertindak sesuai dengan rencana yang telah dibuat.", "SS"),
    (28, "Saya teliti dalam pekerjaan saya.", "SS"),
    (29, "Saya dapat bergaul secara luwes dengan orang-orang yang baru saja saya kenal.", "SS"),
    (30, "Saya berusaha untuk lebih baik dari orang lain.", "SS"),
    (31, "Saya mendukung rekan tim atau anggota kelompok saya.", "SS"),
    (32, "Saya tidak suka banyak bercerita tentang diri saya.", "SS"),
    (33, "Saya cenderung berada di belakang layar.", "TS"),
    (34, "Saya tidak meninggalkan suatu tugas sebelum tugas tersebut terselesaikan.", "SS"),
    (35, "Saya mudah bingung.", "TS"),
    (36, "Saya melanggar peraturan.", "STS"),
    (37, "Saya membiarkan diri saya diperlakukan tidak semestinya.", "STS"),
    (38, "Saya sulit untuk melakukan pendekatan kepada orang lain.", "STS"),
    (40, "Saya mengelak dari tugas-tugas saya.", "STS"),
    (41, "Saya tidak menonjol dalam hal apapun.", "STS"),
    (42, "Saya mampu membuat orang lain untuk melakukan berbagai pekerjaan dengan rapih.", "TS"),
    (43, "Saya menyelesaikan banyak pekerjaan dengan cepat dan rapih.", "SS"),
    (44, "Saya mampu mengikuti banyak informasi sekaligus.", "S"),
    (45, "Saya bekerja dengan penuh ikhlas.", "TS"),
    (46, "Saya membuat perencanaan dan mampu membuat rencana tersebut.", "TS"),
    (47, "Saya adalah orang yang berfokus pada tujuan.", "SS"),
    (48, "Saya mudah berteman.", "S"),
    (49, "Saya ingin menjadi yang terbaik.", "S"),
    (50, "Saya merasa harus banyak menghargai keputusan-keputusan yang dibuat oleh kelompok.", "SS"),
    (51, "Saya cenderung tidak banyak berbicara ketika berada di sekitar orang-orang yang sama sekali tidak dikenal.", "TS"),
    (52, "Saya mengerjakan pekerjaan sesegera mungkin.", "S"),
    (53, "Saya mengerjakan berbagai hal mendekati tenggang waktu.", "STS"),
    (54, "Saya bertindak tanpa perencanaan.", "TS"),
    (55, "Saya mengabaikan tugas-tugas saya.", "STS"),
    (56, "Saya tidak pernah menentang apapun.", "SS"),
    (57, "Saya jarang merasa nyaman ketika berada bersama banyak orang.", "STS"),
    (58, "Saya merasa patah semangat ketika menghadapi hambatan.", "STS"),
    (59, "Saya mengalokasikan sedikit waktu dan usaha dalam bekerja.", "STS"),
    (60, "Saya selalu menghormati orang yang lebih tua.", "SS"),
    (61, "Saya dapat dengan mudah membuat orang lain memperhatikan saya.", "STS"),
    (63, "Saya mampu menghasilkan solusi dengan cepat.", "SS"),
    (64, "Teman-teman menghargai saya karena penilaian saya yang bagus.", "STS"),
    (65, "Saya melakukan hal-hal sesuai dengan rencana yang telah dibuat.", "S"),
    (66, "Saya mudah menyesuaikan diri.", "S"),
    (67, "Saya menetapkan standar yang tinggi untuk diri saya sendiri dan orang lain.", "SS"),
    (68, "Saya berusaha untuk membuat semua orang diterima dan diikutsertakan dalam kelompok.", "STS"),
    (69, "Saya tidak mengutarakan pemikiran saya secara leluasa ketika hal tersebut mungkin memunculkan hasil yang negatif.", "S"),
    (70, "Saya terus melakukan sesuatu sampai semuanya sempurna.", "S"),
    (71, "Seringkali lupa untuk meletakkan barang di tempat yang seharusnya.", "STS"),
    (72, "Saya mengerjakan sesuatu dengan 'setengah-setengah'.", "STS"),
    (73, "Saya menunggu orang lain untuk memimpin.", "STS"),
    (74, "Saya sering terganggu dengan setidaknya salah satu dari anggota kelompok, saat berinteraksi dengan sekelompok orang.", "S"),
    (75, "Saya menyimpan segala sesuatu untuk diri sendiri.", "STS"),
    (76, "Saya tidak pernah berbicara kasar.", "SS"),
    (77, "Saya mampu membuat orang lain merasa tertarik.", "S"),
    (78, "Saya tidak keberatan menjadi pusat perhatian.", "S"),
    (79, "Saya berhasil menyelesaikan tugas.", "SS"),
    (80, "Saya mampu menangani masalah-masalah yang rumit.", "S"),
    (81, "Saya suka menyusun perencanaan sebelum bertindak.", "SS"),
    (82, "Saya fokus pada tujuan.", "SS"),
    (83, "Saya mampu menyesuaikan diri dalam berbagai situasi.", "S"),
    (84, "Saya menuntut kualitas.", "S"),
    (86, "Saya menghindari berhadapan dengan emosi-emosi yang tidak perlu diperhatikan.", "S"),
    (87, "Saya tidak memiliki banyak hal untuk dibicarakan.", "S"),
    (88, "Saya tidak merokok.", "S"),
    (89, "Saya tidak minum.", "TS"),
    (90, "Saya cenderung menghindari materi bacaan yang sulit.", "TS"),
    (91, "Saya meninggalkan pekerjaan saya sebelum terselesaikan.", "STS"),
    (92, "Saya tidak tertarik berspekulasi tentang berbagai hal.", "TS"),
    (93, "Saya enggan mengungkapkan pendapat saya.", "S"),
    (94, "Sulit bagi saya untuk mempengaruhi orang lain untuk melakukan apa yang saya mau.", "S"),
    (95, "Saya sering merasa tidak nyaman ketika berada di sekitar orang-orang.", "TS"),
    (96, "Saya ingin dibiarkan sendirian.", "TS"),
    (97, "Saya memilih untuk melakukan segalanya sendiri.", "TS"),
    (98, "Saya tidak menyelesaikan apa yang telah saya mulai.", "STS"),
    (99, "Saya memiliki ritme kehidupan yang lambat.", "STS"),
    (100, "Saya selalu hadir jika diundang.", "SS"),
    (101, "Saya tidak pernah berbohong.", "SS"),
    (102, "Saya tahu apa saja yang bisa menggugah orang lain.", "TS"),
    (103, "Saya tidak pernah kehabisan kata-kata ketika berbicara.", "TS"),
    (104, "Saya cepat menangkap inti dari berbagai hal.", "S"),
    (105, "Saya mampu menyelesaikan berbagai jenis tugas.", "S"),
    (106, "Saya melaksanakan perencanaan yang telah saya buat.", "S"),
    (107, "Saya berhati-hati agar terhindar dari membuat kesalahan.", "S"),
    (109, "Saya mengambil tanggung jawab.", "SS"),
    (110, "Saya kurang berbakat mempengaruhi orang lain.", "SS"),
    (111, "Saya kurang berbakat mempengaruhi orang lain.", "S"),
    (112, "Saya tidak menyukai perempuan.", "STS"),
    (113, "Saya menangani pekerjaan yang sulit dengan baik.", "SS"),
    (114, "Saya menganggap keterbatasan bagus dan baik.", "S"),
    (115, "Saya kurang menyediakan berbagai makanan yang sehat.", "TS"),
    (116, "Saya tidak dapat menghasilkan ide-ide dengan baik.", "TS"),
    (117, "Saya cenderung menjaga jarak dengan orang lain.", "TS"),
    (118, "Saya kurang pandai bekerja dalam kelompok.", "STS"),
    (119, "Saya merasa bahwa pekerjaan bukanlah bagian yang pernah saya inginkan.", "STS"),
    (120, "Saya mudah menyerah.", "STS"),
    (121, "Saya selalu mematuhi perintah orangtua.", "SS"),
    (122, "Saya cenderung memulai pembicaraan.", "SS"),
    (123, "Saya terampil dalam menghadapi situasi pergaulan.", "S"),
    (124, "Saya menangani banyak tugas dengan lancar.", "S"),
    (125, "Saya pandai dalam berbagai hal.", "S"),
    (126, "Saya mengikuti jadwal.", "SS"),
    (127, "Menjadi bagian dari suatu kelompok merupakan hal yang menyenangkan.", "S"),
    (128, "Saya mempertimbangkan pro dan kontra.", "S"),
    (129, "Saya menjalankan dan menindaklanjuti komitmen yang saya pegang dengan teguh.", "S"),
    (130, "Saya sulit mengungkapkan perasaan saya.", "S"),
    (132, "Saya sering membuat perencanaan-perencanaan di saat senggang.", "S"),
    (133, "Saya tidak tahu cara untuk mengendalikan diri saya.", "TS"),
    (134, "Saya tidak suka berkelahi.", "SS"),
    (135, "Saya suka berolahraga.", "SS"),
    (136, "Saya menganggap bahwa bersosialisasi dengan orang lain itu tidak terlalu penting.", "TS"),
    (137, "Saya meninggalkan barang-barang bawaan di sekitar saya.", "STS"),
    (138, "Saya tidak pernah membicarakan orang lain.", "SS"),
    (139, "Saya berbicara kepada banyak orang yang berbeda-beda dalam suatu pesta.", "S"),
    (140, "Saya memiliki ide-ide yang cemerlang.", "SS"),
    (141, "Saya mampu mengatasi apa pun.", "SS"),
    (142, "Saya mampu bekerja di bawah tekanan.", "SS"),
    (143, "Saya menginginkan segala sesuatunya berjalan sebagaimana mestinya.", "S"),
    (144, "Saya tidak pernah menyerah.", "SS"),
    (145, "Saya sangat tertutup mengenai kehidupan pribadi saya.", "SS"),
    (146, "Saya mudah panik.", "STS"),
    (147, "Saya kurang pandai dalam membuat perencanaan aktivitas kelompok.", "TS"),
    (148, "Saya cenderung bertindak tanpa berpikir terlebih dahulu.", "STS"),
    (149, "Saya menghindari berhubungan dengan orang lain.", "STS"),
    (150, "Saya mudah berkecil hati.", "STS"),
    (151, "Saya selalu ramah kepada orang lain meskipun ia pernah menyakiti saya.", "S"),
    (152, "Saya mengetahui cara untuk memikat atau menarik hati orang lain.", "S"),
    (153, "Saya mampu mengelola berbagai pekerjaan pada saat yang bersamaan.", "S"),
    (155, "Saya mudah terintimidasi.", "STS"),
    (156, "Saya merasa bahwa hidup saya kurang memiliki arah.", "STS"),
    (157, "Saya tidak pernah marah.", "S"),
]

print(f"Total raw items: {len(raw_data)}")

# Deterministic shuffle using a good seed
rng = random.Random(20260925)
shuffled = list(raw_data)
rng.shuffle(shuffled)

# Assign new numbers 1 to 150
final_items = []
for new_num, (orig_num, text, ans) in enumerate(shuffled, start=1):
    final_items.append({
        "new_num": new_num,
        "orig_num": orig_num,
        "text": text,
        "answer": ans
    })

with open("sesi3_shuffled.json", "w", encoding="utf-8") as f:
    json.dump(final_items, f, indent=2, ensure_ascii=False)

print("Saved sesi3_shuffled.json successfully")
